const { Font, FileMenu, Verification } = require("lib");
Tester.createFile("docx");
Font.clickBold();
Tester.keyPress("Enter");
Tester.input("Hello World!");
Tester.keyPress("ArrowLeft");
Tester.keyDown("Shift");
for (let i = 0; i < 5; i++) Tester.keyPress("ArrowLeft");
Tester.keyUp("Shift");
Font.clickBold();
Tester.keyPress("Enter");
Tester.input("Hello World!");
Tester.keyDown("Shift");
for (let i = 0; i < 5; i++) Tester.keyPress("ArrowLeft");
Tester.keyUp("Shift");
FileMenu.downloadAs("docx");
Verification.openFile();
Verification.check("word/document.xml", "//w:p[2]/w:r[1]/w:t[1]/text()[1]", "Hello");
Verification.check("word/document.xml", "//w:p[3]/w:r[1]/w:t[1]/text()[1]", "Hello World!");
Verification.check("word/document.xml", "//w:p[3]/w:r[1]/w:rPr[1]/w:bCs[1]/@w:val", "0");
console.log(Verification.isSuccess());
Tester.close();
